name: My First Workflow
on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  MyFirstJob:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Hello world"
      
      - name: Checkout
        uses: actions/checkout@v6.0.0

      - name: Df
        run: df -h -x tmpfs

      - name: Pwd
        run: pwd

      - name: List files in root
        run: ls --color=never /

      - name: List files in mnt
        run: ls --color=never /mnt

      - name: Cat file in mnt
        run: cat /mnt/DATALOSS_WARNING_README.txt

      - name: List files in home
        run: ls --color=never -a ~/

      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files"
          tree --charset=ascii -n -a .
          
    
    
